### ISSUE TITLE
Support t.Parallel?

### ISSUE THREAD

**Issue by zchee** [uber-go/goleak#16]
Hi, thanks for providing great package :)

BTW, I saw `goleak` internal source and found below `switch...case`:
https://github.com/uber-go/goleak/blob/18742541d022941d2ef0db05d30bc68f69e96bd9/options.go#L118

But, I used `t.Parallel` func on my project testing. So, `goleak` suggested:

```
found unexpected goroutines
```

Is it the expected behavior? Or, Should I adding `goleak.IgnoreTopFunction("testing.(*T).Parallel")` to `defer goleak.VerifyNoLeaks(t)`? (and, is it correct use case?)

**Comment by houqp** [comment]
Got hit by the same issue, is there any reason not to add `t.Parallel` to the whitelist?

**Comment by prashantv** [comment]
I think adding `testing.(*T).Parallel` is reasonable for ignoring tests that are queued to be run later.

I don't think we can support goroutine verification in parallel tests though, since goleak verified all running goroutines, and in parallel tests, the end of a single test may still have many other goroutines running from other tests.

**Comment by zchee** [comment]
@prashantv Thanks for the polite answer. I totally agreed with your thought.
I wait for merge https://github.com/uber-go/goleak/pull/25 pull request :D

**Comment by houqp** [comment]
I think that's reasonable and the behavior should probably be documented :)

In our cases, the tests we run in parallel don't create extra go routines at all, so goleak should still be able to handle it. That said, I think our use-case is probably a pretty restricted edge-case ;)

**Comment by bwplotka** [comment]
Is t.Parrallel() something reasonable as a feature request though? 

It would be really nice to join forces to finally have solution to this: detection of leak go routines and parallel tests. (: 

Related discussion: https://github.com/fortytw2/leaktest/issues/4

**Comment by prashantv** [comment]
I don't think there is a good solution for detecting goroutine leaks from a _test_ when using `t.Parallel` since it's intentionally running with other tests which will definitely have their own running goroutines, and we cannot identify which goroutines are started by which test.

However, there is a workaround: Use the `TestMain` [integration](https://github.com/uber-go/goleak/#quick-start) in the package,
```go
func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m)
}
```

This will verify that there's no leaks after _all_ tests are run.
